# Generated by Django 5.0.2 on 2024-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("des", models.CharField(max_length=500)),
                ("date", models.DateTimeField()),
                ("time", models.TimeField()),
                ("image", models.ImageField(blank=True, upload_to="data")),
            ],
        ),
        migrations.DeleteModel(
            name="person",
        ),
    ]
