# Generated by Django 5.0.2 on 2024-02-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_blogs_delete_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="LatestNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Heading", models.CharField(max_length=500)),
                ("Description", models.CharField(max_length=500)),
                ("image", models.ImageField(blank=True, upload_to="data")),
            ],
        ),
        migrations.CreateModel(
            name="SearchEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("des", models.CharField(max_length=500)),
                ("images", models.ImageField(blank=True, upload_to="data")),
                ("Link", models.URLField()),
            ],
        ),
    ]
