# Generated by Django 5.0.2 on 2024-02-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_faq_answer_alter_faq_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="des",
        ),
        migrations.RemoveField(
            model_name="blogs",
            name="time",
        ),
        migrations.RemoveField(
            model_name="searchengine",
            name="des",
        ),
        migrations.AddField(
            model_name="blogs",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="searchengine",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="latestnews",
            name="Description",
            field=models.TextField(),
        ),
    ]
