# Generated by Django 5.0.2 on 2024-02-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChangePassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_pass", models.CharField(max_length=40)),
                ("new_pass", models.CharField(max_length=40)),
            ],
        ),
    ]
