# Generated by Django 5.0.2 on 2024-02-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_userchangepassword"),
    ]

    operations = [
        migrations.CreateModel(
            name="helpSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=40)),
                ("content", models.TextField(max_length=500)),
            ],
        ),
    ]
