# Generated by Django 5.0.2 on 2024-02-19 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_helpsupport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserChangePassword",
        ),
    ]
